### ISSUE TITLE
Not sure how to get the discord function to work

### ISSUE THREAD

**Issue by FdomEnjoyer** [PetitTournesol/Edgeware#28]
I'm trying to get the discord message to show but I'm not sure how. I have the premade packs and the resource folder set up how its supposed to be but there is no status. Do I need to do anything else or should it just work?

**Comment by PuppyDoll21** [comment]
Hi FdomEnjoyer, there's a small formatting issue in some of the premade packs that's preventing it. Try opening the file Edgeware/resource/discord.dat as a text file, and make sure there's a newline character at the end. It also won't work if you don't have your activity hidden in Discord (check the Activity Privacy section).

**Comment by FdomEnjoyer** [comment]
Hi, thank you for the response. I have tried both of these now, and still no luck. I think that I'll give up on the discord function for now and try to get it working at a later date.
