### ISSUE TITLE
Getting a Major error with popups? 

### ISSUE THREAD

**Issue by Blu3jay9** [PetitTournesol/Edgeware#48]
"CRITICAL:failed to start popup
module 'PIL.Image' has no attribute 'ANTIALIAS' "
as far as I can tell, this thing goes on forever slowly filling the logs with the same prompt shown above 
[Sun_Jul__2_03-16-04_2023-ew_start.txt](https://github.com/PetitTournesol/Edgeware/files/11928979/Sun_Jul__2_03-16-04_2023-ew_start.txt)

**Comment by Sassy0P** [comment]
I think it is the same issue as #47.
I've given some instructions to try to fix it in the said issue.
