### ISSUE TITLE
Pop ups not working on Windows 10 Pro

### ISSUE THREAD

**Issue by nowothing** [PetitTournesol/Edgeware#53]
The pop ups seem to not be working at all to me, I just switched to Windows 10 Pro and now have been facing this bug. There are no error messages or anything, all that happens is a Command Prompt appears for a brief moment from time to time, and the wallpaper is changed succesfully when I open and close it, but no pop ups.

**Comment by Sassy0P** [comment]
Could you check the logs folder or the run debug script and give the output?

This might be linked to #47 as you just reinstalled and there is a problem with the Pillow version

**Comment by nowothing** [comment]
Yup! I checked the logs files and it was the same problem as the issue you linked, thanks a lot for the help.
