### ISSUE TITLE
Config does not work

### ISSUE THREAD

**Issue by TheSirM3** [PetitTournesol/Edgeware#8]
the config file didn't start so i ran the debug tool and got this error from the config file

```
Traceback (most recent call last):
  File "C:\Users\Teresa\Documents\Edgeware-main\EdgeWare\config.pyw", line 942, in <module>
    def write_save(varList:list[StringVar | IntVar | BooleanVar], nameList:list[str], passVar:str, exitAtEnd:bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by TheSirM3** [comment]
does not work in version 2.4.1 so far

**Comment by PetitTournesol** [comment]
This is a problem caused by Python version; updating to Python 3.10.2, should fix the issue! Sorry about that!

**Comment by hauntedtide13** [comment]
> This is a problem caused by Python version; updating to Python 3.10.2, should fix the issue! Sorry about that!

How would one do that? I thought the updated file on here would automatically update everything so it works.

**Comment by TheSirM3** [comment]
I just re installed it from the python website
